a = input(' : ')
print('o tipo primitivo é',type(a))
print('só tem espaço?',a.isspace())
print('é número?',a.isnumeric())
print('é alfabético?', a.isalpha())
print('é alfanumerico?',a.isalnum())
print('Está em maiusculo?',a.isupper())
print('é minusculo?',a.islower())
print('esta capitalizada?',a.istitle())
